config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signin", to: "session#sign_in"
  post "/signin", to: "session#create"
  delete "/signout", to: "session#destroy"
  get "/signup", to: "users#new"
  get "static_pages/about", as: :about
  get "static_pages/home", as: :home
  get "static_pages/help", as: :help
  get "static_pages/contact", as: :contact
  resources :users, except: :new
  resources :courses
  resources :subjects
  resources :tasks, only: :index
  resources :course_subjects
  resources :user_courses, only: %i(create destroy)
  get "/index", to: "index#index"
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :user_subjects, dependent: :destroy
  has_many :course_subjects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :courses, through: :course_subjects

  validates :name_subject, uniqueness: true
  scope :find_subjects_not_in_course, ->(course){where("id NOT IN(?)", course.subject_ids) if course.subject_ids.present?}
  scope :subject, ->(subject_ids){where "id in (?)",subject_ids}
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index; end

  def create; end
end

app/views/subjects/_subject.html.erb
<li>
  <%= link_to subject.name_subject, "#" %>
</li>

app/views/subjects/index.html.erb
<div class="content">
  <section class="content-header">
    <h1>
      <%= t ".sub" %>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i>
        <%= t ".home" %>
      </a></li>
      <li><a href="#"><%= t ".course" %></a></li>
      <li class="active"><%= t ".subject" %></li>
    </ol>
  </section>

  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <h2>
          <%= t ".name" %><small><%= t ".time" %></small>
        </h2>
      </div>
      <div class="box-body">
        <%= t ".detail" %>
      </div>
      <div class="box-footer">
        <%= link_to t(".link"), tasks_path %>
      </div>
    </div>
  </section>
</div>