config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signin", to: "session#sign_in"
  post "/signin", to: "session#create"
  delete "/signout", to: "session#destroy"
  get "/signup", to: "users#new"
  get "static_pages/about", as: :about
  get "static_pages/home", as: :home
  get "static_pages/help", as: :help
  get "static_pages/contact", as: :contact
  resources :users, except: :new
  resources :courses
  resources :subjects
  resources :tasks, only: :index
  resources :course_subjects
  resources :user_courses, only: %i(create destroy)
  get "/index", to: "index#index"
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :user_courses, dependent: :destroy
  has_many :course_subjects, dependent: :destroy
  accepts_nested_attributes_for :course_subjects
  has_many :subjects, through: :course_subjects
  has_many :users, through: :user_courses
  has_many :having, through: :course_subjects, source: :subject
  has_many :having_users, through: :user_courses, source: :user

  scope :order_by_date, ->{order created_at: :desc}

  enum status_course: {init: 0, in_progess: 1, finish: 2}
  validates :name_course, presence: true

  def have subject
    having << subject
  end

  def unhave subject
    having.delete subject
  end

  def have_user user
    having_users << user
  end

  def unhave_user user_courser
    having_user.delete user
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :load_course, :load_subjects, only: %i(show destroy)

  def index
    @courses = Course.order_by_date.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def new
    @course = Course.new
    @course.course_subjects.build
    @subjects = Subject.all
  end

  def show
    load_trainers_trainees @course
    @all_subjects = Subject.find_subjects_not_in_course @course
    @subjects = @course.subjects
  end

  def create
    subject_ids = params[:subject][:subject_ids]
    @course = Course.new course_params
    if @course.save
      flash[:success] = t "flash.success_create_course"
      subject_ids.each do |subject_id|
        @course_subjects = @course.course_subjects.new
        @course_subjects.subject_id = subject_id
        @course_subjects.save
      end
      redirect_to courses_path
    else
      render :new
    end
  end

  def destroy
    if @course.init?
      if @course.destroy
        flash[:success] = t "flash.success_destroy_course"
      else
        flash[:danger] = t "flash.danger_destroy_course"
      end
    else
      flash[:danger] = t "flash.in_progress"
    end
    redirect_to courses_path
  end

  def edit
    load_course
    load_subjects
    load_trainers_trainees @course
    @all_subjects = Subject.find_subjects_not_in_course @course
    @subjects = @course.subjects
    load_trainers
    load_trainees
  end

  def update
    @course = Course.find_by id: params[:id]
    if @course.update_attributes courses_params
      flash[:success] = t "flash.success_update"
      redirect_to courses_path
    else
      flash[:danger] = t "flash.danger_success_update"
      render :edit
    end
  end

  def load_trainers_trainees course
    @trainers = course.users.with_trainerOrtrainee(:trainer).alphabet_name.paginate page: params[:page],
      per_page: Settings.trainer.per_page
    @trainees = course.users.with_trainerOrtrainee(:trainee).alphabet_name.paginate page: params[:page],
      per_page: Settings.trainer.per_page
  end

  def load_subjects
    @subjects = @course.subjects.paginate page: params[:page],
      per_page: Settings.per_page
    @course_subjects = @course.course_subjects.paginate page: params[:page],
      per_page: Settings.per_page
  end

  private

  def load_course
    @course = Course.find_by id: params[:id]
    return if @course
    flash[:danger] = t "flash.danger1"
    redirect_to courses_path
  end

  def course_params
    params.require(:course).permit(:name_course, :info_detail,
      course_subjects_attributes: [:id, :subject_id])
  end

  def courses_params
    params.require(:course).permit(:name_course, :info_detail)
  end

  def load_trainers
    @all_trainers = @course.users.trainer
    @trainerss = User.find_users_not_in_course(@course).trainer
  end

  def load_trainees
    @all_trainers = @course.users.trainee
    @traineess = User.find_users_not_in_course(@course).trainee
  end
end

app/views/courses/_added_subjects.html.erb
<li>
  <%= link_to subject.id, "#" %> . <%= link_to subject.name_subject, "#" %>
  <% if current_user.trainer? %>
    <%= link_to t(".remove"), course_subject_path(subject_id: subject.id), method: :delete, confirm: t(".sure"), class: "btn btn-danger" %>
  <% end %>
</li>

app/views/courses/_added_users.html.erb
<li>
  <%= link_to user.id, "#" %> . <%= link_to user.username, "#" %>
  <% if current_user.trainer? %>
    <%= link_to t(".remove"), user_course_path(user_id: user.id), method: :delete, confirm: t(".sure"), class: "btn btn-danger" %>
  <% end %>
</li>

app/views/courses/_adding_subjects.html.erb
<li>
  <%= link_to subject.id %>.<%= link_to subject.name_subject, "#" %>
  <%= form_for(@course.course_subjects.build) do |f| %>
    <div><%= hidden_field_tag :subject_id, subject.id %></div>
    <div><%= hidden_field_tag :course_id, @course.id %></div>
    <%= f.submit t(".add"), class: "btn btn-success" %>
  <% end %>
</li>

app/views/courses/_adding_users.html.erb
<li>
  <%= link_to user.username, "#" %>
  <% if current_user.trainer? %>
    <%= form_for(@course.user_courses.build) do |f| %>
      <div><%= hidden_field_tag :user_id, user.id %></div>
      <div><%= hidden_field_tag :course_id, @course.id %></div>
      <%= f.submit t(".add"), class: "btn btn-success" %>
    <% end %>
  <% end %>
</li>

app/views/courses/_course.html.erb
<li>
  <%= link_to course.id, "#" %>
  .
  <%= link_to course.name_course, course %>
  <% if current_user.trainer? %>
    | <%= link_to t(".delete"), course, method: :delete, data: {confirm: t(".confirm")} %>
    | <%= link_to t(".edit"), edit_course_path(course) %>
  <% end %>
  <p><%= course.info_detail %></p>
</li>

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
  <%= render "shared/error_messages", object: @course %>
  <div class="field">
    <%= f.label :name_course %>
    <%= f.text_field :name_course, class: "form-control" %>

    <%= f.label :info_detail %>
    <%= f.text_field :info_detail, class: "form-control" %>
  </div>
  <%= f.fields_for @subjects do |f| %>
    <ul>
      <%= collection_check_boxes(:subject, :subject_ids, @subjects, :id, :name_subject) do |b| %>
      <li>
        <%= b.label("data-value": b.value) {b.check_box(class: "check_box")} %>
        <%= b.text %>
      </li>
      <% end %>
    </ul>
  <% end %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/courses/_form_edit.html.erb
<%= form_for @course do |f| %>
  <%= render "shared/error_messages", object: @course %>
  <div class="field">
    <%= f.label :name_course %>
    <%= f.text_field :name_course, class: "form-control" %>

    <%= f.label :info_detail %>
    <%= f.text_field :info_detail, class: "form-control" %>
  </div>
  <br>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/courses/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".update") %>
<h1><%= t ".h1" %><%= @course.name_course %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form_edit"%>
    <br>
  </div>
</div>
<div class="row">
  <div class="col-md-4"><%= t ".subjects" %>
    <ul>
      <%= render partial: "added_subjects", collection: @subjects, as: :subject %>
    </ul>
    <% if current_user.trainer? %>
      <% if @all_subjects.present? %>
        <ul class="ls-sub">
          <p><%= t ".another_sb" %></p>
            <%= render partial: "adding_subjects", collection: @all_subjects, as: :subject %>
              </ul>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-4"><%= t ".trainers" %>
    <ul class="lb-sub">
        <% if @trainers.present? %>
          <%= render partial: "added_users", collection: @trainers, as: :user %>
        <% else %>
          <%= t ".notify_trainer" %>
        <% end %>
        <br><ul class="lb-sub">
          <p><%= t ".another_trainer" %></p>
            <%= render partial: "adding_users", collection: @trainerss, as: :user %>
        </ul>
    </ul>
  </div>
  <div class="col-md-4"><%= t ".trainees" %>
    <ul class="lb-sub">
      <% if @trainees.present? %>
        <%= render partial: "added_users", collection: @trainees, as: :user %>
      <% else %>
        <%= t".notify_trainee" %>
      <% end %>
      <br><ul class="lb-sub">
        <p><%= t ".another_trainee" %></p>
          <%= render partial: "adding_users", collection: @traineess, as: :user %>
      </ul>
    </ul>
  </div>
</div>

app/views/courses/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>
<% if current_user.trainer? %>
  <%= link_to t(".add_btn"), new_course_path, class: "btn btn-primary" %>
<% end %>
<ul class="ls-all">
  <%= render @courses %>
</ul>
<%= will_paginate %>

app/views/courses/new.html.erb
<% provide :title,  t(".title") %>
<% provide :button_text, t(".create") %>
<h1><%= t ".h1" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/courses/show.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <h1><%= @course.name_course %></h1>
  <h2><%= t(".desc") %><%= @course.info_detail %></h2>
  <h2><%= t(".created") %><%= @course.created_at %></h2>
  <table class="table table-striped">
    <thead>
      <th><%= t ".subjects" %></th>
      <th><%= t ".trainers" %></th>
      <th><%= t ".trainees" %></th>
    </thead>
    <tbody>
      <tr>
        <td>
          <ul>
            <%= render partial: "added_subjects", collection: @subjects, as: :subject %>
          </ul>
          <% if current_user.trainer? %>
            <% if @all_subjects.present? %>
              <ul class="ls-sub">
                <p><%= t ".another_sb" %></p>
                <%= render partial: "adding_subjects", collection: @all_subjects, as: :subject %>
              </ul>
            <% end %>
          <% end %>
        </td>
        <td>
            <%= render @trainers %>
        </td>
        <td>
            <%= render @trainees %>
        </td>
      </tr>
    </tbody>
  </table>
</div>