config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signin", to: "session#sign_in"
  post "/signin", to: "session#create"
  delete "/signout", to: "session#destroy"
  get "/signup", to: "users#new"
  get "static_pages/about", as: :about
  get "static_pages/home", as: :home
  get "static_pages/help", as: :help
  get "static_pages/contact", as: :contact
  resources :users, except: :new
  resources :courses
  resources :subjects
  resources :tasks, only: :index
  resources :course_subjects
  resources :user_courses, only: %i(create destroy)
  get "/index", to: "index#index"
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <strong> &copy; <%= t "layouts.footer.copy" %>
    <a href="#"><%= t "layouts.footer.name" %></a>
  </strong>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <%= link_to t(".title"), index_path, class: "logo" %>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only"></span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag current_user.avatar, size: Settings.size.user_image %>
            <span class="hidden-xs"><%= t "layouts.header.account" %><b class="caret"></b></span>
          </a>
          <% if logged_in? %>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <%= image_tag current_user.avatar, size: Settings.size.user_image %>
                <p>
                  <%= current_user.fullname %>
                  <small><%= t "layouts.header.calender" %></small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#"><%= t "layouts.header.followers" %></a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#"><%= t "layouts.header.friends" %></a>
                  </div>
                </div>
                <!-- /.row -->
              </li>

              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <%= link_to user_path(current_user), class: "btn btn-default btn-flat" do %>
                      <%= t "layouts.header.profile" %>
                  <% end%>
                </div>
                <div class="pull-right">
                  <% if current_user.trainer? %>
                    <li><%= link_to t(".signup"), signup_path %></li>
                  <% end %>
                  <li class="divider"></li>
                  <li><%= link_to t(".signout"), signout_path, method: :delete %></li>
                </div>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".resignin"), signin_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_right-bar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
      >
        <%= image_tag current_user.avatar, size: Settings.size.image %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.fullname %></p>
        <a href="#"><%= t "layouts.right-bar.active" %></a>
      </div>
    </div>
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control"
          placeholder= <%= t "layouts.right-bar.search" %> >
          <span class="input-group-btn">
            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
            <i class="fa fa-search"></i>
            </button>
          </span>
      </div>
    </form>
    <ul class="sidebar-menu">
      <li class="header"><%= t "layouts.right-bar.main" %></li>
      <li>
        <a href="/home">
        <i class="fa fa-book"></i>
        <span><%= link_to t(".dashboard"), index_path %></span>
        </a>
      </li>
      <li>
        <a href="/courses">
          <i class="fa fa-circle-o"></i>
          <span>
            <%= t "layouts.right-bar.course" %>
          </span>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-edit"></i>
          <span>
            <%= link_to t(".users"), users_path %>
          </span>
        </a>
      </li>
    </ul>
    </section>
  </aside>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render "layouts/rails_default" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <%= render "layouts/shim" %>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <%= render "layouts/header" %>
      <%= render "layouts/right-bar" %>
      <div class="content-wrapper">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/root_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>